// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      // The extension bundle is generated by esbuild, not written by hand.
      'packages/vscode/out/**',
      '**/node_modules/**',
      '**/coverage/**',
      // Fixtures are inputs to the test suite: they contain deliberate defects
      // and must not be linted or auto-fixed.
      'fixtures/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        // One project covering sources, tests and config files, with package
        // names mapped to sources so linting never needs a prior build.
        project: ['./tsconfig.check.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },
  {
    files: ['**/*.test.ts', '**/test/**/*.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
  {
    // Plain scripts that are not part of any tsconfig project, so the
    // type-aware rules have nothing to read.
    files: ['eslint.config.js', 'vitest.config.ts', '**/scripts/**/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      parserOptions: { project: null },
      globals: { process: 'readonly', URL: 'readonly', console: 'readonly' },
    },
  },
);
